openapi: 3.0.3
info:
  description: Simple endpoints for managing the data from the GamePoll-Bot.
  version: 1.0.0
  title: GamePoll-Bot

servers:
  - url: https://localhost:3000/
    description: Debug server

tags:
  - name: past_messages
    description: Managing the messages for the bot to keep track of
  - name: config
    description: The current config of the bot

paths:
  /config:
    get:
      tags:
        - config
      summary: Show the bot config
      responses:
        "200":
          description: A User object
          content:
            application/json:
              schema:
                type: object
  /past_messages:
    get:
      tags:
        - past_messages
      summary: Show the past messages for the bot to keep track of
      responses:
        "200":
          description: The past messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
              example: [123456789]

  /past_messages/{msgId}:
    post:
      tags:
        - past_messages
      summary: Add an id for the bot to keep track of
      parameters:
        - in: path
          required: true
          name: msgId
          schema:
            type: integer
      responses:
        "200":
          description: The added past message
          content:
            plain/text:
              example: "Added 1234 msgId"
